manage *args:
  docker compose run --rm web uv run --active manage.py {{args}}

migrate:
  just manage migrate

makemigrations:
  just manage makemigrations

rebuild:
  docker compose build web

run *args:
  docker compose up {{args}}

reset:
  docker compose down -v --remove-orphans
  docker compose build web
  just migrate
