manage *args:
  docker compose run --rm web uv run --no-sync --active manage.py {{args}}

migrate:
  just manage migrate

makemigrations:
  just manage makemigrations

rebuild:
  docker compose build web bolt procrastinate

run *args:
  docker compose up {{args}}

reset:
  docker compose down -v --remove-orphans
  docker compose build web
  just migrate

shell:
  just manage shell_plus --ipython
